"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def answer():
    """
    Loops through fibonacci numbers, only adding even numbered that are less
    than 4,000,000
    """
    sum = 0
    f0 = 0
    f1 = 1
    while f1 < 4*10**6:
        # If even, add it
        if f1 & 1 == 0:
            sum += f1

        f0, f1 = f1, f1 + f0

    return sum


if __name__ == "__main__":
    print answer()
