"""
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn = n(3n - 1)/2. The first
ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of
D?
"""
from common.MiscMath import pentagonNumber, isPentagonal


def answer():
    # Start with k = 2
    k = 2
    while True:
        Pk = pentagonNumber(k)

        # Loop through all Pj < Pk
        for j in xrange(1, k):
            Pj = pentagonNumber(j)

            if isPentagonal(Pj + Pk) and isPentagonal(Pk - Pj):
                return Pk - Pj

        k += 1


if __name__ == "__main__":
    print answer()
